# Excercise 2


## 2. Task

In [2]:
import numpy as np

In [110]:
x = np.array([[1], [-2], [3]])
y = np.array([[3], [2], [1]])

tensor_xy = x.dot(np.transpose(y))

print(f"Das Tensorprodukt von x'={np.transpose(x)} und y'={np.transpose(y)} ist \n {tensor_xy}")

Das Tensorprodukt von x'=[[ 1 -2  3]] und y'=[[3 2 1]] ist 
 [[ 3  2  1]
 [-6 -4 -2]
 [ 9  6  3]]


## 3. Task

In [118]:
from scipy import linalg

In [226]:
A = np.array([[1, 2], [2,1]])

# a)
trace_A = np.trace(A)
print(f"Spur von A = {trace_A}", "\n", "-"*40)

# b)
det_A = linalg.det(A)
print(f"Determinante von A = {det_A}", "\n", "-"*40)

# c)
eigvals, eigvecs = np.linalg.eig(A)
lambda1, lambda2 = np.round(eigvals[0]), np.round(eigvals[1])
vec1, vec2 = np.round(eigvecs[0]), np.round(eigvecs[1])

assert det_A == lambda1*lambda2, f"Houston we got a Problem! {det_A} =! {lambda1} * {lambda2}"
assert trace_A == lambda1+lambda2, f"Houston we got another Problem! {trace_A} =! {lambda1} + {lambda2}"

print(f"Eigenwerte: lambda1 = {lambda1}, lambda2 = {lambda2}")
print(f"Eigenvektoren: v1 = {vec1}, v2 = {vec2}")

Spur von A = 2 
 ----------------------------------------
Determinante von A = -3.0 
 ----------------------------------------
Eigenwerte: lambda1 = 3.0, lambda2 = -1.0
Eigenvektoren: v1 = [ 1. -1.], v2 = [1. 1.]


# 4. Task

In [232]:
W = np.array([[3, 1, 0], [1, 3, 0] ,[0, 0, 5/2]])
X = np.array([[1/np.sqrt(2), 1/np.sqrt(3), 1/np.sqrt(6)],
              [1/np.sqrt(2), -1/np.sqrt(3), -1/np.sqrt(6)],
              [0, 1/np.sqrt(3), -2/np.sqrt(6)]])

# a)
inv_W = np.linalg.inv(W)
print(f"Inverse von W: W^-1 = \n{inv_W}", "\n", "-"*40)

# b)
prod_XX = X.dot(np.transpose(X))
print(f"Produkt von X*X' = \n{prod_XX}", "\n", "-"*40)

#c)
inv_X = np.linalg.inv(X)
print(f"Inverse von X: X^-1 = \n{inv_X}")

Inverse von W: W^-1 = 
[[ 0.375 -0.125  0.   ]
 [-0.125  0.375  0.   ]
 [ 0.     0.     0.4  ]] 
 ----------------------------------------
Produkt von X*X' = 
[[ 1.00000000e+00 -2.49570864e-16  4.58633852e-19]
 [-2.49570864e-16  1.00000000e+00 -4.58633852e-19]
 [ 4.58633852e-19 -4.58633852e-19  1.00000000e+00]] 
 ----------------------------------------
Inverse von X: X^-1 = 
[[ 7.07106781e-01  7.07106781e-01  2.84558721e-17]
 [ 5.77350269e-01 -5.77350269e-01  5.77350269e-01]
 [ 4.08248290e-01 -4.08248290e-01 -8.16496581e-01]]


## 5.Task

In [228]:
X = np.array([[-2, -1, 0],
              [2, 1, 0],
              [0, -1, 3],
              [4, 1, 1]])
D = np.array([[np.sqrt(20/3), 0, 0],
              [0, np.sqrt(4/3), 0],
              [0, 0, np.sqrt(2)]])

# a)
# Merke: Inverse von Diagonalmatrix = Diagonalmatrix nur im Kehrbruch
# Merke: axis=0 Spalte, axis=1 Zeile
inv_D = np.linalg.inv(D)
n, p = X.shape[0], X.shape[1]
ones = np.ones((n, 1))
X_mean = X.mean(axis=0, keepdims=True)
# ddof = delta degree of freedom 1/(n-ddof)*..., in matlab etc default is 1, in this case it is 0
X_std = X.std(axis=0, keepdims=True, ddof=1)
assert np.array_equal(np.diag(X.std(axis=0, ddof=1)),D), "Given Standard Derivation from the Exercise does not match computed Standard Derivation by numpy, check if used degree of freedom matches! (argument 'ddof')"

Z1 = (X - X_mean) / X_std
Z2 = (X - ones.dot(X_mean)).dot(inv_D)
print(f"Standardisierte Daten (ohne Centering Matrix): Z = \n{Z1}", "\n", "-"*40)

# b)
emp_corr1 = np.corrcoef(X, rowvar=False)
emp_corr2 = 1/(n-1) * np.transpose(Z1).dot(Z1)
print(f"Empirische Korrelationsmatrix von X: Cor(X) = \n{emp_corr2}")

Standardisierte Daten (ohne Centering Matrix): Z = 
[[-1.161895   -0.8660254  -0.70710678]
 [ 0.38729833  0.8660254  -0.70710678]
 [-0.38729833 -0.8660254   1.41421356]
 [ 1.161895    0.8660254   0.        ]] 
 ----------------------------------------
Empirische Korrelationsmatrix von X: Cor(X) = 
[[ 1.          0.89442719  0.        ]
 [ 0.89442719  1.         -0.40824829]
 [ 0.         -0.40824829  1.        ]]
